// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { join } from "node:path";
import { defineConfig } from "prisma/config";
import { existsSync, readFileSync } from "node:fs";
import { parse } from "dotenv";

const envPath = join(__dirname, ".env");
const envConfig = existsSync(envPath) ? parse(readFileSync(envPath)) : {};

export default defineConfig({
  schema: join(__dirname, "prisma/schema.prisma"),
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --transpile-only prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL || envConfig["DATABASE_URL"],
  },
});
